FROM node:20-alpine

WORKDIR /app

ARG WHATSAPP_API_KEY
ARG FIREBASE_API_KEY
ARG FIREBASE_CLIENT_EMAIL
ARG FIREBASE_PRIVATE_KEY
ARG FIREBASE_PROJECT_ID
ARG WHATSAPP_API_URL
ARG JWT_ACCESS_SECRET
ARG JWT_REFRESH_SECRET

COPY package*.json .
RUN npm ci

COPY . .

ENV WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
ENV FIREBASE_API_KEY=${FIREBASE_API_KEY}
ENV FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
ENV FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
ENV FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
ENV WHATSAPP_API_URL=${WHATSAPP_API_URL}
ENV JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
ENV JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}


RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
